version: '2.0'

services:
  # micro-pattern:
  #   image: micro-pattern
  #   build: .
  #   ports:
  #     - 3000:3000

  ory-hydra-example--postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks: 
      - hydraguide
    volumes: 
      - /hydra-postgres:/var/lib/postgresql/data:z
    labels:
      - traefik.enable=false
      - com.docker.compose.project=hydra-platform

  ory-hydra-example--hydra:
    image: oryd/hydra:v0.11.6
    ports:
      - 9000:4444
    environment:
      - DATABASE_URL=$DATABASE_URL
      - SYSTEM_SECRET=$SYSTEM_SECRET
      - ISSUER=https://localhost:4444
      - CONSENT_URL=http://localhost:9020/consent
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password
    networks: 
      - hydraguide
    depends_on:
      - ory-hydra-example--postgres

  ory-hydra-example--consent:
    image: oryd/hydra-consent-app-express
    ports:
      - 9020:3000
    environment:
      - HYDRA_CLIENT_ID=consent-app
      - HYDRA_CLIENT_SECRET=consent-secret
      - HYDRA_URL=https://ory-hydra-example--hydra:4444
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    networks: 
      - hydraguide
    depends_on:
      - ory-hydra-example--postgres
      - ory-hydra-example--hydra

networks: 
  hydraguide: 
    external: false
    driver: bridge
